### ISSUE TITLE
cannot print receipt at all yaml issues

### ISSUE THREAD

**Issue by hydrosIII** [OpenPymeMx/ProxyPoS#8] opened 2014-06-05 17:09 UTC
Hi i have just tried to install this proxy to print from openerp. i Cannot print any receipt i kept getting errors related to python yaml.

Traceback (most recent call last):
  File "/home/proxypos/proxypos/proxypos/app.py", line 44, in do_print
    device = printer.device()
  File "/home/proxypos/proxypos/proxypos/controlers/printer.py", line 52, in **init**
    self.config = yaml.load(f.read())
  File "/usr/local/lib/python2.7/dist-packages/yaml/**init**.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
ParserError: while parsing a block mapping
  in "<string>", line 2, column 1:
    printer:
    ^
expected <block end>, but found '<block mapping start>'
  in "<string>", line 6, column 3:
      settings:
      ^
2014-06-05 11:17:37,679 - proxypos.app - INFO - Procesing /pos/print_receipt GET method
2014-06-05 11:17:37,680 - proxypos.app - INFO - Already printed receipt by POST methodTraceback (most recent call last):
  File "/home/proxypos/proxypos/proxypos/app.py", line 44, in do_print
    device = printer.device()
  File "/home/proxypos/proxypos/proxypos/controlers/printer.py", line 52, in **init**
    self.config = yaml.load(f.read())
  File "/usr/local/lib/python2.7/dist-packages/yaml/**init**.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
ParserError: while parsing a block mapping
  in "<string>", line 2, column 1:
    printer:
    ^
expected <block end>, but found '<block mapping start>'
  in "<string>", line 6, column 3:
      settings:
      ^
2014-06-05 11:17:37,679 - proxypos.app - INFO - Procesing /pos/print_receipt GET method
2014-06-05 11:17:37,680 - proxypos.app - INFO - Already printed receipt by POST method

Im using debian stable (wheezy), using crunchgbag distro.  trying to work out this issue i have installed pyyaml using pip. The printing fails both with pyyaml from pip and python-yaml from debian repos.

Also here are some corrections to the install instructions:

You need to install also python-simplejson, it is not listed as dependency.

the adduser command is not working, you have to use useradd ( at least in debian).

**Comment by agb80** [comment] 2014-06-06 18:05
Please test new release we just done and let us know if you are still getting troubles to make it work.
Thanks in advance!

**Comment by hydrosIII** [comment] 2014-06-06 20:01
Hi i have tested ne 1.2 version. Still not working, this time proxypos is not starting at all. I suspecto some error in the cofig file. Im using a serial printer. The command proxypos-server gives me this:

 File "/usr/local/bin/proxypos-server", line 5, in <module>
    pkg_resources.run_script('proxypos==1.2.0', 'proxypos-server')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/EGG-INFO/scripts/proxypos-server", line 5, in <module>
    proxypos.main()
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/**init**.py", line 49, in main
    config.import_config(configfile.read())
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/kaptan/**init**.py", line 68, in import_config
    self.configuration_data = self.handler.load(value)
  File "/usr/local/lib/python2.7/dist-packages/proxypos-1.2.0-py2.7.egg/proxypos/proxypos/kaptan/handlers/yaml_handler.py", line 20, in load
    return yaml.load(data)
  File "/usr/lib/python2.7/dist-packages/yaml/**init**.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "<string>", line 72, column 4:
       devfile: /dev/lp0
       ^
expected <block end>, but found '<block mapping start>'
  in "<string>", line 89, column 5:
        WidthA: 42
        ^
both running proxypos-server as root and as normal user. My config file is almost the same as the original. Here is the diff of my config file and the config provided. (  diff proxypos.yaml proxypos.yaml.example )

< #  type: usb       # Uncomment this for an usb printer

## <    type: serial    # Uncomment this for a serial printer

>   type: usb       # Uncomment this for an usb printer
>   # type: serial    # Uncomment this for a serial printer
> 68,69c68,69
> <  #   idVendor: 0x0483
> 
> ## <  #   idProduct: 0x5740
> 
> ```
> idVendor: 0x0483
> idProduct: 0x5740
> ```
> 
> 72c72
> 
> ## <    devfile: /dev/lp0
> 
> ```
> #devfile: /dev/ttyS0      
> ```

Im sorry seems github is formatting the text is some way. !!

**Comment by agb80** [comment] 2014-06-06 22:24
Seems the problem is that when you are editing the file for input your custom configuration you are adding some estrange characters, could be the software you are using to edit the file. 

Try copy again the file and edit using nano or vi

**Comment by hydrosIII** [comment] 2014-06-07 17:22
Custom?? do you mean because of the format on github ?? i think that is
because github grabbed some characters as html code.
I always use nano to edit files. I dont' see any strange characters. here
is my conf file

http://pastebin.com/RX8md4Fe.

Let me try in a clean installation maybe there are issues with previous 1.1
version.

Thanks

2014-06-06 17:24 GMT-05:00 agb80 notifications@github.com:

> Seems the problem is that when you are editing the file for input your
> custom configuration you are adding some estrange characters, could be the
> software you are using to edit the file.
> 
> Try copy again the file and edit using nano or vi
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Fedrojesa/ProxyPoS/issues/8#issuecomment-45390283.

## 

_Por favor, evite enviarme documentos adjuntos en formato Word Excel o
PowerPoint.Como alternativa puede enviarme documentos en formato odt, odx u
ods, además de documentos en formato pdfSi realmente es necesario enviarme
un documento en formato Word, por favor utilize el formato .doc en lugar de
.docx Vea http://www.gnu.org/philosophy/no-word-attachments.html
http://www.gnu.org/philosophy/no-word-attachments.htmlhttp://es.libreoffice.org/
http://es.libreoffice.org/http://getgnulinux.org/es
http://getgnulinux.org/es_

**Comment by hydrosIII** [comment] 2014-06-07 18:34
Hi. i have managed to start succesfully the proxypos-server. You were right there are some characters that yaml is not recognizing. Strangely it works when you use the usb configuration but for the serial configuration the proxy is not acepting any spaces in the lines i mean:

It is not acepting this:
[space]type: serial

But it is aceppting this:

type: serial

Also this only happens in the second part of the config file. So this is strange,also the usb setup is working without deleting spaces.

So now the server is starting but not printing receipts.
here is the error log:

http://pastebin.mozilla.org/5370858

I just erased personal details. we are in mexico and using acents in the ticket but i have tried with different characters sets and it is not working.

Thanks

**Comment by agb80** [comment] 2014-06-07 18:36
The problem i whit the indentation on your config file, for example on line 72 you only have 3 spaces, and must be 4.

Yaml is sensible to indentation just as python.

**Comment by agb80** [comment] 2014-06-07 18:44
Yes, just reviewing the last log file you send and the problem is that ProxyPoS is not recognizing the printer type sentence, don't know if you review the indentation and if that helps you?

We are also in Mexico, and the system is working in production with couple of customers. One of them even use it to print electronic invoices.

**Comment by hydrosIII** [comment] 2014-06-07 20:24
Im going to try to review the identation, so you say it is possible that
this is causing the problem. I always thought that spaces where transparent
in config files. Let me check maybe that is the issue. I will report soon.
Do you mind if i fork the documentation to include this problems???

2014-06-07 13:44 GMT-05:00 agb80 notifications@github.com:

> Yes, just reviewing the last log file you send and the problem is that
> ProxyPoS is not recognizing the printer type sentence, don't know if you
> review the indentation and if that helps you?
> 
> We are also in Mexico, and the system is working in production with couple
> of customers. One of them even use it to print electronic invoices.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Fedrojesa/ProxyPoS/issues/8#issuecomment-45417908.

## 

_Por favor, evite enviarme documentos adjuntos en formato Word Excel o
PowerPoint.Como alternativa puede enviarme documentos en formato odt, odx u
ods, además de documentos en formato pdfSi realmente es necesario enviarme
un documento en formato Word, por favor utilize el formato .doc en lugar de
.docx Vea http://www.gnu.org/philosophy/no-word-attachments.html
http://www.gnu.org/philosophy/no-word-attachments.htmlhttp://es.libreoffice.org/
http://es.libreoffice.org/http://getgnulinux.org/es
http://getgnulinux.org/es_

**Comment by hydrosIII** [comment] 2014-06-07 20:58
Ok i have tested it with a new config file where i carefully modified it taking in account the spaces. So this is an improvement.. But i m still not able to print. But i think Yaml has nothing to do this time . Im posting the error log and also my config file. 

error:
http://pastebin.com/rnqVefKz

config 

http://pastebin.com/ndcXzw6C

Maybe i should open a new issue for this one.

Tehre seems to be sintax error in some python lines im proxypos.

**Comment by agb80** [comment] 2014-06-07 21:43
Glad you solve yaml problems, will be a pleasure if you propose a PR with the changes on the documentation for make a better understatement and facilitate installation for future users. Please refer this issue on your PR so we can close this when documentation will be improved.

Please open another issue regarding the issue you found with serial printers, just a quick comment 

```
SerialException: Could not configure port: (22, 'Invalid argument')
```

Does the printer is still on port /dev/ttyS4 as you put in your configuration file?

**Comment by hydrosIII** [comment] 2014-06-08 19:01
It is in /dev/lp0 but that this not the issue. I have tried to print both
in lp0 and ttyS4, ttyS4 is just a symbolic link to /dev/lp0, ( i have
created it) to try to  see if it worked because the documetation says
something about ttyS*, but i have also tried with /dev/lp0. The permissions
of the node are set to 777, so that is not the problem. I can also print
from terminal using echo to both nodes. I will open another issue.

Thanks.

2014-06-07 16:43 GMT-05:00 agb80 notifications@github.com:

> Glad you solve yaml problems, will be a pleasure if you propose a PR with
> the changes on the documentation for make a better understatement and
> facilitate installation for future users. Please refer this issue on your
> PR so we can close this when documentation will be improved.
> 
> Please open another issue regarding the issue you found with serial
> printers, just a quick comment
> 
> SerialException: Could not configure port: (22, 'Invalid argument')
> 
> Does the printer is still on port /dev/ttyS4 as you put in your
> configuration file?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Fedrojesa/ProxyPoS/issues/8#issuecomment-45421977.

## 

_Por favor, evite enviarme documentos adjuntos en formato Word Excel o
PowerPoint.Como alternativa puede enviarme documentos en formato odt, odx u
ods, además de documentos en formato pdfSi realmente es necesario enviarme
un documento en formato Word, por favor utilize el formato .doc en lugar de
.docx Vea http://www.gnu.org/philosophy/no-word-attachments.html
http://www.gnu.org/philosophy/no-word-attachments.htmlhttp://es.libreoffice.org/
http://es.libreoffice.org/http://getgnulinux.org/es
http://getgnulinux.org/es_

**Comment by agb80** [comment] 2014-06-09 20:22
There are two options then:
1. baudrate pre-definied on software is not working for you
2. your printer is not using serial communication, less probable.

Please open a new issue for review this!

**Closed as completed** 2014-06-09 20:23 UTC
